### ISSUE TITLE
v1.0.1 introduces a dependency on python

### ISSUE THREAD

**Issue by akalman** [crypto-browserify/EVP_BytesToKey#10]
we are using webpack during a build in aws and through a massive dependency chain this library is run as part of that.  our ami's don't have access to python and since 1.0.1 we are seeing failures akin to this:

```
evp_bytestokey@1.0.1 install /opt/app/projectdashboard/node_modules/evp_bytestokey
node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@7.3.0 | linux | x64
gyp ERR! configure error
gyp ERR! Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

**Comment by akalman** [comment]
nvm it looks like you've already addressed this.

**Comment by dcousens** [comment]
Duplicate of https://github.com/crypto-browserify/EVP_BytesToKey/issues/9
