### ISSUE TITLE
安装EVP_BytesToKey报错，麻烦大神看下，昨天还是好的，今天安装就报下面的错误了

### ISSUE THREAD

**Issue by jingleding** [crypto-browserify/EVP_BytesToKey#12]
npm WARN prefer global voc@1.0.0 should be installed with -g

> evp_bytestokey@1.0.1 install /data/www/java/master2/workspace/nodejs-order-trade-boss/test/node_modules/evp_bytestokey

> node-gyp rebuild

gyp: binding.gyp not found (cwd: /data/www/java/master2/workspace/nodejs-order-trade-boss/test/node_modules/evp_bytestokey) while trying to load binding.gyp

gyp err! configure error

gyp err! stack error: `gyp` failed with exit code: 1

gyp ERR! stack at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/configure.js:305:16)

gyp ERR! stack at emitTwo (events.js:106:13)

gyp ERR! stack at ChildProcess.emit (events.js:191:7)

gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

gyp ERR! System Linux 3.10.0-327.28.2.el7.x86_64

gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /data/www/java/master2/workspace/nodejs-order-trade-boss/test/node_modules/evp_bytestokey

gyp ERR! node -v v6.9.1

gyp ERR! node-gyp -v v3.4.0

gyp ERR! not ok

**Comment by dcousens** [comment]
Please see https://github.com/crypto-browserify/EVP_BytesToKey/issues/9
