### ISSUE TITLE
How to specify how many rounds?

### ISSUE THREAD

**Issue by michael-ts** [crypto-browserify/EVP_BytesToKey#17]
The `EVP_BytesToKey` function takes a "count" parameter specifying how many rounds or iterations to apply the hash for.

**Comment by calvinmetcalf** [comment]
you don't, this is written explicitly for compatibility with some very questionable node.js stdlib usage, you should NEVER be using this as it's insecure as hell so I'm curious why you'd even want the count param

**Comment by michael-ts** [comment]
Ah ok, my bad.  I was looking for some code for compatibility with decrypting stuff encrypted by OpenSSL's EVP_BytesToKey and mistakenly thought this was for that.

**Comment by calvinmetcalf** [comment]
this would be a good start for that
