### ISSUE TITLE
can i use it on rc4 algorithm

### ISSUE THREAD

**Issue by rainx** [crypto-browserify/EVP_BytesToKey#2]
cool project, i am working on a project using rc4 algorithm now ... what kind of params shold i use on this condition , i tried keylen 16 and ,ivlen 0 ,but it seems not work properly ..

**Comment by rainx** [comment]
ok.. i think i used wrong keylen , i changed to 16 * 8 , and it works now

    var keys = evp(password, false, 16 * 8, 0)
    var nodeCipher = crypto.createCipher('rc4', password)
    var ourCipher = crypto.createCipheriv('rc4', keys.key, keys.iv)

TAP version 13
# password: password
ok 1 should be equal
# password: ふっかつ　あきる　すぶり　はやい　つける　まゆげ　たんさん　みんぞく　ねほりはほり　せまい　たいまつばな　ひはん
ok 2 should be equal
# password: Z͑ͫ̓ͪ̂ͫ̽͏̴̙̤̞͉͚̯̞̠͍A̴̵̜̰͔ͫ͗͢L̠ͨͧͩ͘G̴̻͈͍͔̹̑͗̎̅͛́Ǫ̵̹̻̝̳͂̌̌͘!͖̬̰̙̗̿̋ͥͥ̂ͣ̐́́͜͞
ok 3 should be equal
# password: 💩
ok 4 should be equal

1..4
# tests 4
# pass  4

# ok

**Comment by calvinmetcalf** [comment]
yeah I likely need more docs but looks like you figured it out
