### ISSUE TITLE
create-hash/md5

### ISSUE THREAD

**Issue by fanatid** [crypto-browserify/EVP_BytesToKey#3]
``` js
var md5 = require('create-hash/md5')
```

should be

``` js
var createHash = require('create-hash')
function md5 (buf) { return createHash('md5').update(buf).digest() }
```

isn't it?

because
- nobody guarantee that file `md5` will always exists
- you require js version instead openssl in node

ping @calvinmetcalf

**Comment by calvinmetcalf** [comment]
this intentionally grabs just the md5 stuff to avoid pulling in all of the sha and ripemd code when all that is needed is md5.  Also since in context createCipher only ever does a single round we don't really need to worry about teh speed.

**Comment by fanatid** [comment]
I understand that is pulled only `md5`, but it's not right since this is not documented in `create-hash`?

**Comment by calvinmetcalf** [comment]
then lets document it in create-hash

**Comment by fanatid** [comment]
I prefer change require whole create-hash or extract md5 from create-hash

**Comment by dcousens** [comment]
Closing in favour of https://github.com/crypto-browserify/EVP_BytesToKey/pull/6
