### ISSUE TITLE
result.password is returning undefined

### ISSUE THREAD

**Issue by aayush-practo** [crypto-browserify/EVP_BytesToKey#5]
Following [this](https://nodejs.org/api/crypto.html#crypto_crypto_createcipher_algorithm_password) I am trying to run `var result = EVP_BytesToKey('abcdefghhjik', null, 256, 0);` and getting result.password is undefined. same is the case when I am trying to pass salt and setting iv length to 128, 256, 512

**Comment by dcousens** [comment]
@aayush-practo why close/

**Comment by aayush-practo** [comment]
@dcousens  I was supposed to browse result.key and was accessing result.password, anyways I just got a doubt, as mentioned [here](https://nodejs.org/api/crypto.html#crypto_crypto_createcipher_algorithm_password), what should i pass the iv and key length so that I'll get the exact keys and iv being generated by the algorithm for encryption?

**Comment by dcousens** [comment]
Why are you using this anyway?  The recommendation is to use `pbkdf2`?

**Comment by aayush-practo** [comment]
We are actually changing tech stack from node to rails, and to support legacy database where we were encrypting using `createCipher()` algorithm, I have to find the exact gem in ruby but all the encryption algorithms in ruby needs key and iv.

**Comment by dcousens** [comment]
The fact it needs a key and IV won't change,  `EVP_BytesToKey` is just an old OpenSSL nuance which uses MD5 to stretch a key.  You probably don't want to use it unless you have to.

**Comment by aayush-practo** [comment]
Its mentioned in the description of crypto.createCipher [here](https://nodejs.org/api/crypto.html#crypto_crypto_createcipher_algorithm_password) 

> The implementation of crypto.createCipher() derives keys using the OpenSSL function EVP_BytesToKey 

That's why I was trying to find out what exact keys and iv are being generated, so that I can use them in encryption algorithms in rails

**Comment by calvinmetcalf** [comment]
I have a [blog post](http://calvinmetcalf.com/post/104082905653/porting-nodejs-crypto-to-the-browser-part-1-all) where I discuss this, the relevent code is

```js
 function EVP_BytesToKey(password, len) {
	var buff = md5(password);
	var out = buff;
	while (buff.length < len) {
	    buff = md5(buff + password);
	    out += buff;
	}
	return buff.slice(0, len);
}
```
